# 1. Image de base
FROM python:3.10-slim

# 2. Installer les bibliothèques système manquantes (libGL pour OpenCV)
RUN apt-get update && \
    apt-get install -y libgl1-mesa-glx && \
    apt-get clean

# 3. Dossier de travail
WORKDIR /app

# 4. Copier les fichiers
COPY . .

# 5. Installer les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# 6. Exposer le port Flask
EXPOSE 5000

# 7. Lancer l'application avec Gunicorn
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "app:app"]
